version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "security-team"
    assignees:
      - "security-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for specific packages that need manual review
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "devops-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/deployments/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "devops-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Enable version updates for Terraform
  - package-ecosystem: "terraform"
    directory: "/deployments/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "infrastructure-team"
    assignees:
      - "infrastructure-team"
    commit-message:
      prefix: "terraform"
      include: "scope"