# =============================================================================
# Claude Guardian - MINIMAL Stack (Current Reality)
# Only what's actually implemented and working
# =============================================================================

services:
  # Claude Guardian MCP Server - The ONLY service that actually works
  claude-guardian-mcp:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11-slim
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install websockets fastapi uvicorn pydantic
        COPY scripts/ ./scripts/
        COPY config/ ./config/
        EXPOSE 8083
        CMD ["python3", "scripts/start-mcp-service.py", "--port", "8083"]
    container_name: claude-guardian-mcp
    restart: unless-stopped
    environment:
      - MCP_PORT=8083
      - MCP_HOST=0.0.0.0
      - SECURITY_LEVEL=${SECURITY_LEVEL:-moderate}
    ports:
      - "127.0.0.1:8083:8083"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8083/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

# Note: No Qdrant, PostgreSQL, or LightRAG because they're not actually used
# by the current MCP implementation. This is honest about what works.