# =============================================================================
# Claude Guardian - Simplified Production Stack
# Complete stack with LightRAG included, reduced complexity
# =============================================================================

services:
  # Vector database for threat patterns and embeddings
  qdrant:
    image: qdrant/qdrant:latest
    container_name: claude-guardian-qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334" 
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 3s
      retries: 10

  # LightRAG service for intelligent security information retrieval
  lightrag:
    image: ghcr.io/yourorg/lightrag-api:latest
    container_name: claude-guardian-lightrag
    restart: unless-stopped
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
    expose:
      - "8000"
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  # PostgreSQL for audit logs and policies
  postgres:
    image: postgres:17-alpine
    container_name: claude-guardian-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-claude_guardian}
      - POSTGRES_USER=${POSTGRES_USER:-cguser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployments/production/init/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10

  # Claude Guardian MCP Server - Main service endpoint
  claude-guardian-mcp:
    image: ghcr.io/yourorg/claude-guardian-mcp:latest
    container_name: claude-guardian-mcp
    restart: unless-stopped
    environment:
      # Core MCP Configuration
      - MCP_PORT=8083
      - MCP_HOST=0.0.0.0
      
      # Service URLs
      - QDRANT_URL=http://qdrant:6333
      - LIGHTRAG_URL=http://lightrag:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-cguser}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-claude_guardian}
      
      # Security Settings
      - JWT_SECRET=${JWT_SECRET}
      - SECURITY_LEVEL=${SECURITY_LEVEL:-moderate}
      
    ports:
      - "127.0.0.1:8083:8083"   # MCP endpoint - local access only
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      lightrag:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:8083/health"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  qdrant_data:
    driver: local
  postgres_data:
    driver: local

networks:
  default:
    name: claude-guardian-network