global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Claude Guardian MCP service metrics
  - job_name: 'claude-guardian-mcp'
    static_configs:
      - targets: ['claude-guardian-mcp:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Qdrant vector database metrics  
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s
    # Uncomment if postgres_exporter is deployed:
    # - job_name: 'postgres-exporter'
    #   static_configs:
    #     - targets: ['postgres-exporter:9187']

  # System metrics (requires node_exporter)  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093