name: Feature Request
description: Suggest an idea for IFF-Guardian
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched the existing issues to make sure this feature hasn't already been requested
          required: true
        - label: I have read the project roadmap and documentation
          required: true
        - label: This feature request is specific to IFF-Guardian and not a general Python/web development question
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature request fall under?
      options:
        - Core Functionality
        - API Enhancement
        - User Interface
        - Performance
        - Security
        - Documentation
        - DevOps/Infrastructure
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
        - Critical - Blocking my adoption/usage
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches could be..."
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases and scenarios where this feature would be beneficial
      placeholder: |
        1. As a user, I want to... so that...
        2. When working with..., I need to...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what would make this feature request complete
      placeholder: |
        - [ ] Feature should do X
        - [ ] Feature should handle Y case
        - [ ] Feature should be configurable via Z
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions
      description: If you have ideas about how this could be implemented, please share them
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to the implementation?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide detailed requirements and specifications

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here
    validations:
      required: false