name: Security Vulnerability Report
description: Report a security vulnerability (for non-critical issues only)
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
assignees: ["security-team"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT SECURITY NOTICE** ⚠️
        
        **For critical security vulnerabilities, DO NOT create a public issue.**
        
        Please email security-critical issues directly to: **security@iff-guardian.com**
        
        This form should only be used for:
        - Low-severity security improvements
        - Security-related feature requests  
        - General security hardening suggestions
        - Non-exploitable security observations

  - type: checkboxes
    id: severity_check
    attributes:
      label: Severity Confirmation
      description: Please confirm this is NOT a critical security issue
      options:
        - label: This is NOT a critical security vulnerability that could lead to data breach, system compromise, or unauthorized access
          required: true
        - label: I have read the Security Policy and understand when to use private disclosure
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity
      description: What is the estimated severity of this security issue?
      options:
        - Low - Security hardening suggestion
        - Low - Minor information disclosure
        - Medium - Requires user interaction to exploit
        - "I'm not sure - please help me assess"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - Cryptography
        - Dependencies
        - Configuration
        - Infrastructure
        - Information Disclosure
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security issue or improvement suggestion
      placeholder: "Please provide details about the security concern..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this security issue?
      placeholder: "What could an attacker potentially do? What data/systems could be affected?"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If this is a vulnerability, provide steps to reproduce (for non-critical issues only)
      placeholder: |
        1. Step one
        2. Step two
        3. Observe the security issue
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix or mitigate this issue?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      placeholder: |
        - IFF-Guardian version:
        - Operating System:
        - Python version:
        - Deployment method:
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
    validations:
      required: false