# Security Policy Configuration

# Authentication Settings
authentication:
  providers:
    - name: "local"
      enabled: true
      priority: 1
    - name: "oauth2"
      enabled: true
      priority: 2
      providers:
        - google
        - microsoft
        - github
    - name: "saml"
      enabled: false
      priority: 3
      
  session:
    timeout_minutes: 30
    idle_timeout_minutes: 15
    absolute_timeout_hours: 8
    secure_cookies: true
    same_site: "strict"
    http_only: true
    
  multi_factor:
    enabled: true
    required_for_admin: true
    totp_enabled: true
    sms_enabled: false
    email_enabled: true
    backup_codes: 10

# Authorization Settings  
authorization:
  rbac:
    enabled: true
    default_role: "user"
    role_hierarchy:
      - super_admin
      - admin
      - security_analyst
      - operator
      - user
      - guest
      
  permissions:
    granular: true
    resource_based: true
    action_based: true
    
  access_control:
    principle_of_least_privilege: true
    regular_review_required: true
    review_interval_days: 90

# Password Policy
password_policy:
  min_length: 12
  max_length: 128
  require_uppercase: true
  require_lowercase: true
  require_digits: true
  require_special_chars: true
  special_chars: "!@#$%^&*()_+-=[]{}|;:,.<>?"
  
  complexity:
    min_character_sets: 3
    no_common_passwords: true
    no_user_info: true
    no_repeated_chars: 3
    
  history:
    remember_passwords: 12
    min_age_hours: 24
    max_age_days: 90
    
  lockout:
    max_attempts: 5
    lockout_duration_minutes: 30
    progressive_lockout: true

# Encryption Settings
encryption:
  data_at_rest:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
  data_in_transit:
    tls_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    hsts_enabled: true
    hsts_max_age: 31536000
    
  key_management:
    external_kms: true
    key_escrow: false
    key_rotation_automatic: true

# Network Security
network_security:
  firewall:
    enabled: true
    default_deny: true
    whitelist_mode: true
    
  ip_filtering:
    enabled: true
    allow_list: []
    deny_list: []
    geo_blocking: []
    
  rate_limiting:
    global_limit: 1000
    per_user_limit: 100
    per_ip_limit: 50
    window_minutes: 60
    
  ddos_protection:
    enabled: true
    threshold: 10000
    mitigation_automatic: true

# API Security
api_security:
  authentication_required: true
  authorization_required: true
  rate_limiting: true
  input_validation: true
  output_filtering: true
  
  versioning:
    enabled: true
    deprecation_notice_days: 90
    sunset_notice_days: 180
    
  cors:
    strict_origin_policy: true
    preflight_max_age: 86400
    
  headers:
    security_headers: true
    content_security_policy: true
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"

# Data Protection
data_protection:
  classification:
    enabled: true
    levels:
      - public
      - internal
      - confidential
      - restricted
      
  retention:
    automatic_cleanup: true
    default_retention_days: 2555  # 7 years
    
  privacy:
    gdpr_compliance: true
    data_minimization: true
    right_to_erasure: true
    data_portability: true
    
  backup:
    encryption: true
    offsite_storage: true
    retention_policy: true
    recovery_testing: true

# Audit and Logging
audit:
  enabled: true
  comprehensive_logging: true
  log_retention_days: 2555  # 7 years
  
  events:
    - authentication
    - authorization
    - data_access
    - configuration_changes
    - system_events
    - security_events
    
  real_time_monitoring: true
  alert_on_suspicious_activity: true
  automated_response: true

# Incident Response
incident_response:
  automated_detection: true
  immediate_notification: true
  containment_procedures: true
  
  escalation_matrix:
    - level: 1
      response_time_minutes: 15
      personnel: ["security_analyst"]
    - level: 2
      response_time_minutes: 30
      personnel: ["security_analyst", "admin"]
    - level: 3
      response_time_minutes: 60
      personnel: ["security_analyst", "admin", "ciso"]
      
  communication:
    internal_notification: true
    external_notification: true
    regulatory_reporting: true

# Vulnerability Management
vulnerability_management:
  scanning:
    frequency: "daily"
    scope: "comprehensive"
    automated: true
    
  patching:
    critical_patches_hours: 24
    high_patches_days: 7
    medium_patches_days: 30
    low_patches_days: 90
    
  assessment:
    penetration_testing: true
    frequency_months: 6
    external_audits: true

# Compliance
compliance:
  frameworks:
    - "ISO 27001"
    - "SOC 2 Type II"
    - "GDPR"
    - "HIPAA"
    - "PCI DSS"
    
  continuous_monitoring: true
  automated_compliance_checks: true
  regular_assessments: true
  
  reporting:
    frequency: "quarterly"
    automated: true
    stakeholder_distribution: true